// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLinkToPlaylist(arg1, arg2, arg3) {
  return window['go']['core']['App']['AddLinkToPlaylist'](arg1, arg2, arg3);
}

export function Cancel() {
  return window['go']['core']['App']['Cancel']();
}

export function CheckUpdate() {
  return window['go']['core']['App']['CheckUpdate']();
}

export function ChooseDirectory() {
  return window['go']['core']['App']['ChooseDirectory']();
}

export function ChooseYtDlpFile() {
  return window['go']['core']['App']['ChooseYtDlpFile']();
}

export function ClearLogs() {
  return window['go']['core']['App']['ClearLogs']();
}

export function ClearTags() {
  return window['go']['core']['App']['ClearTags']();
}

export function DownloadAndProcess(arg1) {
  return window['go']['core']['App']['DownloadAndProcess'](arg1);
}

export function DownloadGooglePlaylist(arg1) {
  return window['go']['core']['App']['DownloadGooglePlaylist'](arg1);
}

export function DownloadGooglePlaylistAndProcess(arg1) {
  return window['go']['core']['App']['DownloadGooglePlaylistAndProcess'](arg1);
}

export function DownloadLink(arg1) {
  return window['go']['core']['App']['DownloadLink'](arg1);
}

export function DownloadLinkAndProcess(arg1) {
  return window['go']['core']['App']['DownloadLinkAndProcess'](arg1);
}

export function DownloadPlaylist(arg1) {
  return window['go']['core']['App']['DownloadPlaylist'](arg1);
}

export function EmptyGooglePlaylist(arg1) {
  return window['go']['core']['App']['EmptyGooglePlaylist'](arg1);
}

export function GetConfig() {
  return window['go']['core']['App']['GetConfig']();
}

export function GetState() {
  return window['go']['core']['App']['GetState']();
}

export function GooglePlaylists() {
  return window['go']['core']['App']['GooglePlaylists']();
}

export function GoogleSignIn() {
  return window['go']['core']['App']['GoogleSignIn']();
}

export function GoogleSignOut() {
  return window['go']['core']['App']['GoogleSignOut']();
}

export function InstallFFmpeg() {
  return window['go']['core']['App']['InstallFFmpeg']();
}

export function InstallUpdate() {
  return window['go']['core']['App']['InstallUpdate']();
}

export function InstallYtDlp() {
  return window['go']['core']['App']['InstallYtDlp']();
}

export function MarkUpdateSeen(arg1) {
  return window['go']['core']['App']['MarkUpdateSeen'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['core']['App']['OpenFolder'](arg1);
}

export function ProcessAll(arg1) {
  return window['go']['core']['App']['ProcessAll'](arg1);
}

export function RefreshGooglePlaylists() {
  return window['go']['core']['App']['RefreshGooglePlaylists']();
}

export function ResetConfig() {
  return window['go']['core']['App']['ResetConfig']();
}

export function ResolveTagPrompt(arg1, arg2, arg3) {
  return window['go']['core']['App']['ResolveTagPrompt'](arg1, arg2, arg3);
}

export function Scan() {
  return window['go']['core']['App']['Scan']();
}

export function SelectFolder() {
  return window['go']['core']['App']['SelectFolder']();
}

export function SetAsDefault(arg1, arg2) {
  return window['go']['core']['App']['SetAsDefault'](arg1, arg2);
}

export function SetConfig(arg1) {
  return window['go']['core']['App']['SetConfig'](arg1);
}

export function SetFolder(arg1) {
  return window['go']['core']['App']['SetFolder'](arg1);
}

export function SetOptions(arg1, arg2, arg3) {
  return window['go']['core']['App']['SetOptions'](arg1, arg2, arg3);
}

export function SetPlaylistPrefs(arg1, arg2) {
  return window['go']['core']['App']['SetPlaylistPrefs'](arg1, arg2);
}

export function SetPlaylists(arg1) {
  return window['go']['core']['App']['SetPlaylists'](arg1);
}

export function SetWatchEnabled(arg1) {
  return window['go']['core']['App']['SetWatchEnabled'](arg1);
}

export function SetYtDlpConfig(arg1, arg2) {
  return window['go']['core']['App']['SetYtDlpConfig'](arg1, arg2);
}

export function SuggestTrackNames(arg1) {
  return window['go']['core']['App']['SuggestTrackNames'](arg1);
}

export function SyncSettings() {
  return window['go']['core']['App']['SyncSettings']();
}

export function UninstallFFmpeg() {
  return window['go']['core']['App']['UninstallFFmpeg']();
}

export function UninstallYtDlp() {
  return window['go']['core']['App']['UninstallYtDlp']();
}
