// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['core']['App']['Cancel']();
}

export function CheckUpdate() {
  return window['go']['core']['App']['CheckUpdate']();
}

export function ChooseDirectory() {
  return window['go']['core']['App']['ChooseDirectory']();
}

export function ChooseYtDlpFile() {
  return window['go']['core']['App']['ChooseYtDlpFile']();
}

export function ClearLogs() {
  return window['go']['core']['App']['ClearLogs']();
}

export function ClearTags() {
  return window['go']['core']['App']['ClearTags']();
}

export function DownloadPlaylist(arg1) {
  return window['go']['core']['App']['DownloadPlaylist'](arg1);
}

export function GetConfig() {
  return window['go']['core']['App']['GetConfig']();
}

export function GetState() {
  return window['go']['core']['App']['GetState']();
}

export function InstallFFmpeg() {
  return window['go']['core']['App']['InstallFFmpeg']();
}

export function InstallUpdate() {
  return window['go']['core']['App']['InstallUpdate']();
}

export function InstallYtDlp() {
  return window['go']['core']['App']['InstallYtDlp']();
}

export function MarkUpdateSeen(arg1) {
  return window['go']['core']['App']['MarkUpdateSeen'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['core']['App']['OpenFolder'](arg1);
}

export function ProcessAll() {
  return window['go']['core']['App']['ProcessAll']();
}

export function ResetConfig() {
  return window['go']['core']['App']['ResetConfig']();
}

export function ResolveTagPrompt(arg1, arg2, arg3) {
  return window['go']['core']['App']['ResolveTagPrompt'](arg1, arg2, arg3);
}

export function Scan() {
  return window['go']['core']['App']['Scan']();
}

export function SelectFolder() {
  return window['go']['core']['App']['SelectFolder']();
}

export function SetAsDefault(arg1, arg2) {
  return window['go']['core']['App']['SetAsDefault'](arg1, arg2);
}

export function SetConfig(arg1) {
  return window['go']['core']['App']['SetConfig'](arg1);
}

export function SetFolder(arg1) {
  return window['go']['core']['App']['SetFolder'](arg1);
}

export function SetOptions(arg1, arg2, arg3) {
  return window['go']['core']['App']['SetOptions'](arg1, arg2, arg3);
}

export function SetPlaylists(arg1) {
  return window['go']['core']['App']['SetPlaylists'](arg1);
}

export function SetWatchEnabled(arg1) {
  return window['go']['core']['App']['SetWatchEnabled'](arg1);
}

export function SetYtDlpConfig(arg1, arg2) {
  return window['go']['core']['App']['SetYtDlpConfig'](arg1, arg2);
}

export function UninstallYtDlp() {
  return window['go']['core']['App']['UninstallYtDlp']();
}
