// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {rules} from '../models';
import {playlist} from '../models';

export function Cancel():Promise<core.ActionResponse>;

export function CheckUpdate():Promise<core.ActionResponse>;

export function ChooseDirectory():Promise<string>;

export function ChooseYtDlpFile():Promise<string>;

export function ClearLogs():Promise<core.ActionResponse>;

export function ClearTags():Promise<core.ActionResponse>;

export function DownloadAndProcess(arg1:string):Promise<core.ActionResponse>;

export function DownloadPlaylist(arg1:string):Promise<core.ActionResponse>;

export function GetConfig():Promise<core.ActionResponse>;

export function GetState():Promise<core.ActionResponse>;

export function InstallFFmpeg():Promise<core.ActionResponse>;

export function InstallUpdate():Promise<core.ActionResponse>;

export function InstallYtDlp():Promise<core.ActionResponse>;

export function MarkUpdateSeen(arg1:string):Promise<core.ActionResponse>;

export function OpenFolder(arg1:string):Promise<core.ActionResponse>;

export function ProcessAll(arg1:Array<string>):Promise<core.ActionResponse>;

export function ResetConfig():Promise<core.ActionResponse>;

export function ResolveTagPrompt(arg1:string,arg2:boolean,arg3:string):Promise<core.ActionResponse>;

export function Scan():Promise<core.ActionResponse>;

export function SelectFolder():Promise<core.ActionResponse>;

export function SetAsDefault(arg1:rules.Config,arg2:Array<playlist.Playlist>):Promise<core.ActionResponse>;

export function SetConfig(arg1:rules.Config):Promise<core.ActionResponse>;

export function SetFolder(arg1:string):Promise<core.ActionResponse>;

export function SetOptions(arg1:boolean,arg2:string,arg3:boolean):Promise<core.ActionResponse>;

export function SetPlaylists(arg1:Array<playlist.Playlist>):Promise<core.ActionResponse>;

export function SetWatchEnabled(arg1:boolean):Promise<core.ActionResponse>;

export function SetYtDlpConfig(arg1:boolean,arg2:string):Promise<core.ActionResponse>;

export function UninstallFFmpeg():Promise<core.ActionResponse>;

export function UninstallYtDlp():Promise<core.ActionResponse>;
