// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {rules} from '../models';

export function ChooseDirectory():Promise<string>;

export function ClearLogs():Promise<main.ActionResponse>;

export function GetConfig():Promise<main.ActionResponse>;

export function GetState():Promise<main.ActionResponse>;

export function ProcessAll():Promise<main.ActionResponse>;

export function ResetConfig():Promise<main.ActionResponse>;

export function Scan():Promise<main.ActionResponse>;

export function SelectFolder():Promise<main.ActionResponse>;

export function SetAsDefault(arg1:rules.Config):Promise<main.ActionResponse>;

export function SetConfig(arg1:rules.Config):Promise<main.ActionResponse>;

export function SetFolder(arg1:string):Promise<main.ActionResponse>;

export function SetOptions(arg1:boolean,arg2:string,arg3:boolean):Promise<main.ActionResponse>;
