// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ProcessAll() {
  return window['go']['main']['App']['ProcessAll']();
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAsDefault(arg1) {
  return window['go']['main']['App']['SetAsDefault'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetFolder(arg1) {
  return window['go']['main']['App']['SetFolder'](arg1);
}

export function SetOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOptions'](arg1, arg2, arg3);
}

export function SetWatchEnabled(arg1) {
  return window['go']['main']['App']['SetWatchEnabled'](arg1);
}
